name: AquaCoreBreak
version: '${version}'
main: com.aquacore.breakplugin.AquaCoreBreak
api-version: '1.21'
authors: [jumke, Antigravity]
description: A plugin to modify block drops when broken by hand.
commands:
  aquacorebreak:
    description: Main command for AquaCoreBreak
    aliases: [acb]
    usage: /aquacorebreak reload
permissions:
  aquacorebreak.admin:
    description: Allows use of admin commands
    default: op
